from django.shortcuts import render
from django.http import HttpResponse

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer, ChatterBotCorpusTrainer


bot = ChatBot('chatbot', read_only=False,
              logic_adapters=[{
                  'import_path': 'chatterbot.logic.BestMatch',
                  'default_response': 'Sorry, I am a simple ChatBot. I am not yet trained to respond to that.',
                  'maximum_similarity_threshold': 0.99
              }])

list_to_train = [
    "Hi",
    "Hello, how can I help you?",
    "Heya",
    "Hey, how can I help you?",
    "What is your name?",
    "I am just a ChatBot. Care to give me a name?",
    "How are you?",
    "I'm great! Thanks for asking.",
    "Thanks",
    "You're welcome",
    "What can you do?",
    "I can chat with you :)",
    "Who are you?",
    "I am a ChatBot",
    "What do you think about artificial intelligence?",
    "Artificial intelligence is a fascinating field that has the potential to revolutionize many aspects of our lives.",
    "Have you heard about blockchain technology?",
    "Yes, blockchain technology is an innovative way to securely record transactions and create decentralized systems.",
    "What's your opinion on virtual reality?",
    "Virtual reality offers immersive experiences that can transport users to different worlds and scenarios.",
    "Can you explain how self-driving cars work?",
    "Self-driving cars use a combination of sensors, cameras, and algorithms to navigate roads autonomously.",
    "Do you know anything about quantum computing?",
    "Quantum computing leverages the principles of quantum mechanics to perform complex calculations at incredible speeds.",
    "What's your favorite cuisine?",
    "My favorite cuisine is Italian, especially pasta and pizza!",
    "Have you ever tried sushi?",
    "Yes, sushi is delicious! I love the combination of fresh fish and rice.",
    "Do you like spicy food?",
    "I enjoy spicy food, but I can't handle too much heat!",
    "Where are you from?",
    "I exist in the digital world!",
    "What can you do?",
    "I can help answer your questions!",
    "Do you like food?",
    "I don't eat, but I can talk about it!",
    "Have you traveled anywhere recently?",
    "I wish! But I'm here to chat with you.",
    "What's your favorite hobby?",
    "I enjoy learning new things!",
    "Have you heard any gossip lately?",
    "I'm not really into gossip!",
    "Seen any good movies?",
    "I don't watch movies, but I can discuss them!",
    "What's happening in the news?",
    "I'm not up-to-date, but I can try to find out!",
    "Do you have any pets?",
    "I'm just a virtual assistant, no pets for me!",
    "What's your favorite color?",
    "I don't have preferences like humans do!",
    "What do you do for fun?",
    "Chatting with you is fun for me!",
    "Do you enjoy music?",
    "I don't have ears, but I can discuss music!",
    "What's your favorite type of weather?",
    "I don't experience weather, but I can talk about it!",
    "Are you a morning person or a night owl?",
    "I don't sleep, so I'm available any time!",
    "Do you like to cook?",
    "I don't cook, but I can share recipes!",
    "What's your favorite season?",
    "I don't have preferences, but I can discuss the seasons!",
    "Have you ever been to a concert?",
    "I haven't, but I can imagine it's exciting!",
    "What's your opinion on social media?",
    "I don't have personal opinions, but it's a popular topic!",
    "Do you enjoy outdoor activities?",
    "I don't have a physical form, but I can talk about outdoor activities!",
    "What's your favorite holiday?",
    "I don't celebrate holidays, but I can discuss them!",
    "Have you ever tried meditation?",
    "I'm always calm and collected!",
    "What's your favorite type of exercise?",
    "I don't exercise, but I can talk about it!",
    "Do you have any siblings?",
    "I'm a solo virtual assistant!",
    "What's your favorite type of book?",
    "I don't read, but I can discuss different genres!",
    "Have you ever gone camping?",
    "I haven't, but I can imagine it's a great adventure!",
    "What's your favorite type of dessert?",
    "I don't eat, but I can talk about delicious desserts!",
    "Do you enjoy watching sports?",
    "I don't watch sports, but I can discuss them!",
    "What's your favorite type of art?",
    "I appreciate all forms of art!",
    "Have you ever gone scuba diving?",
    "I haven't, but I can imagine it's an amazing experience!",
    "What's your favorite type of movie genre?",
    "I don't watch movies, but I can discuss different genres!",
    "Do you enjoy gardening?",
    "I don't have a green thumb, but I can talk about gardening!",
    "What's your favorite type of technology?",
    "I'm a fan of all kinds of technology!",
    "Have you ever gone skydiving?",
    "I haven't, but I can imagine it's exhilarating!",
    "Do you like to travel?",
    "I don't travel, but I can talk about it!",
    "What's your favorite type of cuisine?",
    "I don't eat, but I can discuss different cuisines!",
    "Are you a fan of technology?",
    "I'm a virtual assistant, so yes!",
    "What's your favorite type of music?",
    "I don't have ears, but I can discuss different music genres!",
    "Do you enjoy learning new things?",
    "I'm always eager to learn!",
    "What's your favorite animal?",
    "I don't have preferences, but I can talk about animals!",
    "Are you interested in history?",
    "I'm fascinated by history!",
    "What's your favorite type of movie?",
    "I don't watch movies, but I can discuss different types!",
    "Do you like to read?",
    "I don't read, but I can discuss different genres of books!",
    "What's your favorite way to relax?",
    "I'm always relaxed and ready to chat!",
    "Are you a creative person?",
    "I'm a virtual assistant, so I can help with creativity!",
    "Do you enjoy spending time outdoors?",
    "I don't have a physical form, but I can talk about outdoor activities!",
    "What's your favorite type of drink?",
    "I don't drink, but I can talk about different beverages!",
    "Are you a fan of art?",
    "I appreciate all forms of art!",
    "What's your favorite type of transportation?",
    "I don't travel, but I can discuss different modes of transportation!",
    "Do you like to exercise?",
    "I don't exercise, but I can talk about it!",
    "What's your favorite type of weather?",
    "I don't experience weather, but I can discuss it!",
    "Are you interested in science?",
    "I'm fascinated by science!",
    "What's your favorite type of holiday?",
    "I don't celebrate holidays, but I can talk about them!",
    "Do you enjoy spending time with friends?",
    "I'm always here to chat with you!",
    "What's your favorite type of food?",
    "I don't eat, but I can discuss different types of cuisine!",
    "Do you like to watch TV shows?",
    "I don't watch TV, but I can talk about different shows!",
    "What's your favorite type of sport?",
    "I don't watch sports, but I can discuss different sports!",
    "Are you interested in fashion?",
    "I don't have preferences, but I can discuss fashion trends!",
    "Do you enjoy listening to podcasts?",
    "I don't listen to podcasts, but I can discuss different topics!",
    "What's your favorite type of exercise?",
    "I don't exercise, but I can talk about it!",
    "Are you a fan of board games?",
    "I don't play games, but I can discuss different types!",
    "What's your favorite type of technology?",
    "I'm a fan of all kinds of technology!",
    "Do you like to take photographs?",
    "I don't have a camera, but I can appreciate photography!",
    "What's your favorite type of dessert?",
    "I don't eat, but I can discuss different desserts!",
    "Are you interested in space exploration?",
    "I'm fascinated by space exploration!",
    "Do you enjoy spending time outdoors?",
    "I don't have a physical form, but I can talk about outdoor activities!",
    "What's your favorite type of movie genre?",
    "I don't watch movies, but I can discuss different genres!",
    "Are you a fan of music concerts?",
    "I don't attend concerts, but I can talk about different music genres!",
    "What's your favorite type of art?",
    "I appreciate all forms of art!",
    "Do you like to travel by train?",
    "I don't travel, but I can discuss different modes of transportation!",
    "What's your favorite type of book?",
    "I don't read, but I can discuss different genres!",
    "Are you interested in learning new languages?",
    "I'm always eager to learn new things!",
    "What's the best pizza topping in your opinion?",
    "Personally, I think the best pizza topping is pepperoni, but everyone has their own preference.",
    "How do you feel about vegetarianism?",
    "Vegetarianism is a great lifestyle choice for many people, promoting health and sustainability.",
    "What's your dream travel destination?",
    "My dream travel destination is Japan. I'd love to explore its rich culture and beautiful landscapes.",
    "Have you been on any memorable road trips?",
    "Yes, I've been on some amazing road trips, especially along the scenic coastlines.",
    "Do you prefer beach vacations or mountain getaways?",
    "I enjoy both beach vacations and mountain getaways, depending on my mood!",
    "What's the most exotic place you've ever visited?",
    "The most exotic place I've visited is Thailand, with its vibrant cities and stunning beaches.",
    "Any travel tips for someone visiting a new country?",
    "When visiting a new country, it's essential to respect local customs and traditions while exploring.",
    "Have you ever been to Paris?",
    "Yes, Paris is a beautiful city known for its art, architecture, and culinary delights.",
    "What's your favorite local hangout spot?",
    "My favorite local hangout spot is a cozy café where I can relax and enjoy a good book.",
    "Can you recommend a cozy café in the city?",
    "I recommend trying out a quaint café in the city center for a cozy atmosphere and delicious coffee.",
    "What's the best hiking trail in the area?",
    "The best hiking trail in the area offers breathtaking views of the surrounding mountains and forests.",
    "Do you know any hidden gems off the beaten path?",
    "Some hidden gems off the beaten path include charming villages and secluded beaches waiting to be discovered.",
    "What do you like to do in your free time?",
    "In my free time, I enjoy reading, writing, and exploring nature.",
    "Have you ever tried painting or drawing?",
    "Yes, painting and drawing are great ways to express creativity and unwind after a long day.",
    "Do you enjoy playing musical instruments?",
    "I play the guitar and piano, which helps me relax and express myself through music.",
    "Have you attempted any DIY projects recently?",
    "Yes, DIY projects are a fun way to learn new skills and personalize my living space.",
    "Any favorite books or movies you'd recommend?",
    "I'm currently reading [Book Title], and I recently watched [Movie Title], both of which I highly recommend!",
    "Did you hear about the latest celebrity scandal?",
    "Yes, celebrity scandals are often exaggerated by the media, but they do provide entertainment and intrigue.",
    "What's the buzz around town these days?",
    "The buzz around town lately seems to be about upcoming events and new restaurant openings.",
    "Have you seen the latest fashion trends?",
    "Fashion trends come and go, but it's always interesting to see what's popular each season.",
    "Can you spill any juicy gossip?",
    "I can't spill any juicy gossip, but I can assure you there's always something going on!",
    "Do you follow any celebrity gossip blogs?",
    "I occasionally browse celebrity gossip blogs for entertainment, but I take everything with a grain of salt.",
    "What's the best movie you've seen recently?",
    "The best movie I've seen recently is [Movie Title]. It had a great plot and fantastic performances.",
    "Have you watched any classic films lately?",
    "Yes, classic films have a timeless appeal, and I enjoy watching them to appreciate cinematic history.",
    "Do you prefer action movies or romantic comedies?",
    "I enjoy both action movies for their adrenaline-pumping scenes and romantic comedies for their heartwarming stories.",
    "Can you recommend a good documentary?",
    "I recently watched a documentary about [Topic], which was both informative and thought-provoking.",
    "Have you ever attended a film festival?",
    "Yes, film festivals are fantastic opportunities to discover new talent and watch unique indie films.",
    "What's your take on the recent political developments?",
    "Political developments can have significant implications for society, and it's essential to stay informed and engaged.",
    "Have you been following the news about climate change?",
    "Yes, climate change is a pressing issue that requires global cooperation and action to address.",
    "What's happening in the stock market?",
    "The stock market can be volatile, influenced by various factors such as economic indicators and investor sentiment.",
    "Any major events or headlines catching your attention?",
    "Major events and headlines often dominate the news cycle, reflecting the ever-changing world we live in.",
    "How do you stay informed about current affairs?",
    "I stay informed about current affairs by reading news articles, watching documentaries, and discussing with others.",
    "Do you believe in aliens or extraterrestrial life?",
    "The existence of aliens or extraterrestrial life is a fascinating topic that continues to captivate scientists and enthusiasts alike.",
    "What's your opinion on the future of space exploration?",
    "Space exploration holds immense potential for humanity's future, from colonizing other planets to discovering new scientific breakthroughs.",
    "Have you ever experienced deja vu?",
    "Yes, deja vu is a strange phenomenon that many people experience, often leading to feelings of familiarity and curiosity.",
    "Can you recommend any podcasts or YouTube channels?",
    "There are countless podcasts and YouTube channels covering a wide range of topics, catering to diverse interests and preferences.",
    "What's your philosophy on life?",
    "My philosophy on life is to live authentically, seek growth and fulfillment, and contribute positively to the world around me."
]

list_trainer = ListTrainer(bot)
list_trainer.train(list_to_train)
#
#
# chatterbotCorpusTrainer = ChatterBotCorpusTrainer(bot)
# chatterbotCorpusTrainer.train('chatterbot.corpus.english')


def index(request):
    return render(request, 'chat/index.html')


def getResponse(request):
    userMessage = request.GET.get('userMessage')
    chatResponse = str(bot.get_response(userMessage))
    return HttpResponse(chatResponse)
